name: XML-FOAF
version: 0.03
abstract: Parse FOAF (Friend of a Friend) data
author: Benjamin Trott <ben+cpan@stupidfool.org>
license: perl
distribution_type: module
requires:
  RDF::Core: 0
  URI: 0
recommends:
  Crypt::OpenPGP: 1.03
no_index:
  directory:
    - t
    - inc
generated_by: Module::Install version 0.36
